//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanosF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModulosEntities : DbContext
    {
        public ModulosEntities()
            : base("name=ModulosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Licencia> Licencia { get; set; }
        public virtual DbSet<nomina> nomina { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Salidas_Empleados> Salidas_Empleados { get; set; }
        public virtual DbSet<vacaciones> vacaciones { get; set; }
    }
}
